# Generated by Django 6.0.1 on 2026-01-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('BYN', 'Belarusian Ruble'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='BYN', max_length=3),
        ),
    ]
